#!/usr/bin/env node
/**
 * omc-slim — mutation check for file-ledger.
 *
 * Run: node hooks/file-ledger.mutate.mjs
 */

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { runMutants } from "./mutate-runner.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));

const MUTANTS = [
  ["additionalContext emitted",
   'process.stdout.write(JSON.stringify({ suppressOutput: true }));',
   'process.stdout.write(JSON.stringify({ suppressOutput: true, hookSpecificOutput: { additionalContext: "x" } }));',
   "FileChanged injection is a per-write prefix tax"],
  ["exit code 1",
   "  process.exit(0);\n}",
   "  process.exit(1);\n}",
   "breaks always-exits-0"],
  ["ledger key shortened to 12 hex chars",
   '.digest("hex").slice(0, 16)',
   '.digest("hex").slice(0, 12)',
   "the reader derives a 16-char key and opens a ledger that is never written"],
  ["CLAUDE_CONFIG_DIR ignored",
   '  return process.env.CLAUDE_CONFIG_DIR || join(homedir(), ".claude");',
   '  return join(homedir(), ".claude");',
   "a user with a relocated config dir gets a ledger the reader never opens"],
  ["cwd hashed without realpath",
   "    return realpathSync(path);",
   "    return resolve(path);",
   "a session opened through a symlinked path writes a ledger the reader keys differently"],
  ["t stamped with the delivery time",
   "    return statSync(path).mtimeMs;",
   "    return Date.now();",
   "a write is dated 0.5-0.7 s late and lands in the wrong turn"],
  ["session_id dropped from the row",
   "session_id: sessionId, ",
   "",
   "the reader cannot scope rows to the session that wrote them"],
  ["rows written without a session_id",
   '  if (typeof sessionId !== "string" || sessionId === "") return emit();\n',
   "",
   "a row the reader cannot attribute is written anyway"],
  ["empty session_id accepted",
   '  if (typeof sessionId !== "string" || sessionId === "") return emit();',
   '  if (typeof sessionId !== "string") return emit();',
   "a row with an empty session_id is written and matches no session"],
  [".claude writes are ledgered",
   '  if (parts.includes(".claude")) return true;',
   "  if (false) return true;",
   "an 'always allow' click counts as a project edit"],
  ["never-source directories are ledgered",
   "  return parts.some((part) => SKIP.has(part));",
   "  return false;",
   "install noise fills the ledger"],
  ["venv dropped from SKIP",
   '  "venv",\n',
   "",
   "a pip install fills the ledger the same way node_modules would"],
  ["build back in the ledger SKIP",
   '  "vendor",\n',
   '  "vendor",\n  "build",\n',
   "a src/build/ module is never ledgered"],
  ["SKIP matched on cwd's own path",
   "  const parts = relative(cwd, path).split(/[/\\\\]/);",
   "  const parts = path.split(/[/\\\\]/);",
   "a project under vendor/ or ~/.claude is never ledgered"],
  ["relative file_path stored raw",
   "  const path = resolve(cwd, filePath);",
   "  const path = filePath;",
   "the reader's containment test calls every relative write an outside one"],
  ["event forced to change",
   '  appendFileSync(dest, row(sessionId, path, data.event ?? "change"));',
   '  appendFileSync(dest, row(sessionId, path, "change"));',
   "an unlink reads as an edit"],
  ["lstat guard removed",
   "  if (!writableLedger(dest)) {",
   "  if (false) {",
   "a symlink at the ledger path is appended through into its target"],
  ["size cap removed",
   "  return st.isFile() && st.size <= MAX_BYTES;",
   "  return st.isFile();",
   "a multi-megabyte foreign file is appended to and rewritten"],
  ["ledgers directory never created",
   "  mkdirSync(dirname(dest), { recursive: true });\n",
   "",
   "the first append of every project fails and nothing is ever recorded"],
  ["hysteresis removed: rewrite past 500",
   "  if (lines.length <= TRIM_ABOVE_ROWS) return;",
   "  if (lines.length <= KEEP_ROWS) return;",
   "every append past 500 rows is followed by a full rewrite and a second FileChanged"],
  ["trim never runs",
   "  if (lines.length <= TRIM_ABOVE_ROWS) return;",
   "  if (true) return;",
   "the ledger grows until the 1 MiB guard refuses it, then records nothing"],
  ["trim keeps the oldest rows",
   "  writeFileSync(tmp, lines.slice(-KEEP_ROWS).join(\"\\n\") + \"\\n\");",
   "  writeFileSync(tmp, lines.slice(0, KEEP_ROWS).join(\"\\n\") + \"\\n\");",
   "every new write is dropped once the ledger is full"],
  ["rename replaced by a direct write",
   "  writeFileSync(tmp, lines.slice(-KEEP_ROWS).join(\"\\n\") + \"\\n\");\n  renameSync(tmp, dest);",
   "  writeFileSync(dest, lines.slice(-KEEP_ROWS).join(\"\\n\") + \"\\n\");",
   "a reader can observe a truncated ledger mid-rewrite"],
];

process.exit(
  runMutants({
    hook: join(HERE, "file-ledger.mjs"),
    test: join(HERE, "file-ledger.test.mjs"),
    mutants: MUTANTS,
  }),
);
