#!/usr/bin/env node
/**
 * omc-slim — mutation check for seed-watch-paths.
 *
 * "root gate removed" is not listed: on any machine a test can run
 * unprivileged, `/` holds no project marker, so the marker gate refuses it
 * whether the root gate is there or not, and the mutant cannot be killed.
 * The inverted form below is what can be measured.
 *
 * Run: node hooks/seed-watch-paths.mutate.mjs
 */

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { runMutants } from "./mutate-runner.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));

const MUTANTS = [
  ["additionalContext emitted",
   "      watchPaths,",
   '      watchPaths,\n      additionalContext: "indexed",',
   "SessionStart dump busts prefix cache across sessions"],
  ["exit code 1",
   "  process.exit(0);\n}",
   "  process.exit(1);\n}",
   "breaks always-exits-0"],
  ["continue:false emitted",
   "  const out = { suppressOutput: true };",
   '  const out = { suppressOutput: true, continue: false };',
   "halts the session while exiting 0"],
  ["home gate removed",
   "  if (dir === realpathOrResolve(homedir())) return false;\n",
   "",
   "a shell opened in ~ watches Library, Documents and Downloads"],
  ["root gate inverted",
   "  if (parse(dir).root === dir) return false;",
   "  if (parse(dir).root !== dir) return false;",
   "every project is refused and only / could be watched"],
  ["marker gate removed",
   "  return MARKERS.some((marker) => existsSync(join(dir, marker)));",
   "  return true;",
   "a shell opened in ~/Downloads or /tmp watches whatever is there"],
  ["Makefile dropped from MARKERS",
   '  "Makefile",\n',
   "",
   "a C project with no other marker is never watched"],
  ["requirements.txt dropped from MARKERS",
   '  "requirements.txt",\n',
   "",
   "a pip project with no other marker is never watched"],
  ["cap removed",
   "  return [...dirs, ...files].slice(0, MAX_ROOTS);",
   "  return [...dirs, ...files];",
   "a wide tree seeds hundreds of recursive watchers"],
  ["cap raised to 64",
   "const MAX_ROOTS = 48;",
   "const MAX_ROOTS = 64;",
   "the published cap is not the enforced one"],
  ["files take precedence under the cap",
   "  return [...dirs, ...files].slice(0, MAX_ROOTS);",
   "  return [...files, ...dirs].slice(0, MAX_ROOTS);",
   "twenty root-level files push source directories past the cap"],
  ["descent removed",
   "  if (!WORKSPACE_DIRS.has(entry.name)) return [entry.path];",
   "  if (true) return [entry.path];",
   "packages/ is one root and every package's node_modules is a descendant of it"],
  ["every directory descended",
   "  if (!WORKSPACE_DIRS.has(entry.name)) return [entry.path];",
   "  if (false) return [entry.path];",
   "a src/ holding a package.json somewhere below is split into its grandchildren"],
  ["workspace marker check removed",
   "  if (!isWorkspace) return [entry.path];\n",
   "",
   "a plain packages/ of documents is descended and its files go unwatched"],
  ["descent stops at the package",
   "  return children.flatMap((child) => realDirs(child));",
   "  return children;",
   "packages/foo is the root and packages/foo/node_modules is walked"],
  ["a package directory is watched whole",
   "  if (isPackage(entry.path)) return realDirs(entry.path);\n",
   "",
   "frontend/ is the root and frontend/node_modules is walked under it"],
  ["the source tree is not named first",
   "    .sort(byPriority)\n",
   "",
   "src is the root the cap drops for fifty generated modules"],
  ["root-level files not watched",
   "  const files = found.filter(isSourceFile).map((entry) => entry.path);",
   "  const files = [];",
   "a project of main.py and Makefile is never watched"],
  ["lockfiles, databases and logs are watched",
   "  return entry.stat.isFile() && !NOISE_FILE.test(entry.name);",
   "  return entry.stat.isFile();",
   "every install rewrites the lockfile and spawns a hook process for it"],
  ["dotfiles and dot-directories are watched",
   '    if (name.startsWith(".") || SKIP.has(name)) continue;',
   "    if (SKIP.has(name)) continue;",
   ".github and .env are watched, and every .claude settings write fires"],
  ["SKIP not applied",
   '    if (name.startsWith(".") || SKIP.has(name)) continue;',
   '    if (name.startsWith(".")) continue;',
   "the watcher follows every install and livelocks the ledger"],
  ["build dropped from the first-level set",
   '  "build",\n',
   "",
   "a top-level build/ output tree is walked and every compile fires"],
  ["venv dropped from SKIP",
   '  "venv",\n',
   "",
   "the watcher follows every pip install"],
  ["bin back in SKIP",
   '  "env",\n',
   '  "env",\n  "bin",\n',
   "a Rails bin/ is never watched, so its edits never reach the ledger"],
  ["symlinks are followed",
   'import { existsSync, lstatSync, readdirSync, readFileSync, realpathSync } from "node:fs";',
   'import { existsSync, statSync as lstatSync, readdirSync, readFileSync, realpathSync } from "node:fs";',
   "a linked data -> /huge/tree is walked by chokidar"],
  ["isDirectory forced true",
   "    .filter((entry) => entry.stat.isDirectory())\n    .sort(byPriority)\n",
   "    .sort(byPriority)\n",
   "every first-level file and symlink is named as a watch root"],
  ["relative cwd accepted",
   '  if (typeof cwd !== "string" || !isAbsolute(cwd)) return [];',
   '  if (typeof cwd !== "string") return [];',
   "relative watchPaths resolve against whatever directory the watcher runs in"],
];

process.exit(
  await runMutants({
    hook: join(HERE, "seed-watch-paths.mjs"),
    test: join(HERE, "seed-watch-paths.test.mjs"),
    mutants: MUTANTS,
  }),
);
