#!/usr/bin/env node
/**
 * omc-slim — mutation check for the verify-deliverables harness.
 *
 * Breaks the hook on purpose, and asserts the harness notices every time. A
 * SURVIVED line is a hole in the tests, not a bug in the hook. Several mutants
 * here — `additionalContext`, `continue: false`, `decision: "block"` — re-enter
 * or halt a session while still exiting 0, which is what an exit-code assertion
 * alone cannot see.
 *
 * Two regressions are left out because no fixture can observe them, and a
 * mutant nothing can kill measures nothing. Restoring recursion to `unwrap`: a
 * segment is capped at 64 tokens before it is unwrapped, so the deepest
 * recursion that cap admits cannot overflow a stack. Starting Stop's tail read
 * at offset 0: that is the whole-file read, and it reaches the same verdicts
 * more slowly.
 *
 * The runner it calls is shared with the other hooks' mutation suites and holds
 * the sandbox discipline: mutants go to a temp copy, and the tracked hook is
 * only ever read.
 *
 * Run: node hooks/verify-deliverables.mutate.mjs
 */

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { runMutants } from "./mutate-runner.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));

/**
 * [label, find, replace, what breaks in production]
 */
const MUTANTS = [
  ["additionalContext emitted",
   "JSON.stringify({ systemMessage: message, suppressOutput: true })",
   'JSON.stringify({ systemMessage: message, suppressOutput: true, hookSpecificOutput: { additionalContext: "x" } })',
   "re-injects into the finishing subagent"],
  ["continue:false emitted",
   "JSON.stringify({ suppressOutput: true })",
   'JSON.stringify({ suppressOutput: true, continue: false, stopReason: "x" })',
   "halts the session while exiting 0"],
  ["debug writes to stdout",
   'console.error("[omc-slim]", ...args)',
   'console.log("[omc-slim]", ...args)',
   "corrupts the JSON payload"],
  ["scan deadline removed",
   "if ((scanned++ & 0xff) === 0 && Date.now() >= deadline) {",
   "if (false) {",
   "unbounded scan on a pathological transcript, and the 5 s in hooks.json is advisory"],
  // Mutated to return the evidence gathered so far: the scan is a collection,
  // and answering from one that stopped early is the shape the wrong
  // implementation takes.
  ["scan deadline accuses instead of abstaining",
   'debug("cannot tell: scan budget exhausted", scanned);\n      return null;',
   'debug("cannot tell: scan budget exhausted", scanned);\n      return scan;',
   "a slow scan becomes a false accusation against an agent that did write"],
  ["cap check removed",
   "if (size > MAX_TRANSCRIPT_BYTES) {",
   "if (false) {",
   "unbounded read"],
  ["regular-file check removed",
   "if (!st.isFile()) {",
   "if (false) {",
   "hangs forever on a FIFO or character device, breaking 'always exits 0'"],
  ["lstat weakened to stat",
   "st = lstatSync(transcriptPath);",
   "st = statSync(transcriptPath);",
   "follows a symlink to an arbitrary path"],
  ["parent transcript fallback",
   "const agentTranscript = data.agent_transcript_path ?? null;",
   "const agentTranscript = data.agent_transcript_path ?? data.transcript_path ?? null;",
   "credits the main thread's edits to the subagent"],
  ["namespaced name leaks into message",
   "advisories.push(noWriteAdvisory(bare));",
   "advisories.push(noWriteAdvisory(agent));",
   "user sees 'omc-slim:fixer'"],
  ["designer dropped from WRITE_AGENTS",
   'new Set(["fixer", "designer"])',
   'new Set(["fixer"])',
   "half the registered agents stop being checked"],
  ["failed tool_result counts as success",
   "node.is_error !== true",
   "true",
   "a denied write becomes a deliverable"],
  ["null treated as no-write",
   '} else if (wrote === "none") {',
   "} else if (wrote !== true) {",
   "cries wolf when it cannot tell"],
  ["depth bound cut to 2",
   "if (depth > 6 ||",
   "if (depth > 2 ||",
   "misses real blocks at depth 3"],
  ["MultiEdit dropped from WRITE_TOOLS",
   '"NotebookEdit", "MultiEdit"',
   '"NotebookEdit"',
   "MultiEdit stops counting as a write"],
  ["Write dropped from WRITE_TOOLS",
   '"Edit", "Write"',
   '"Edit"',
   "the commonest write tool stops counting, and every Write-only run is accused"],
  ["NotebookEdit dropped from WRITE_TOOLS",
   '"Write", "NotebookEdit"',
   '"Write"',
   "a notebook edit stops counting as a write"],
  ["blank scan budget parsed as zero",
   'if (raw === undefined || raw.trim() === "") return 2000;',
   "if (raw === undefined) return 2000;",
   "an exported-but-empty override mutes the hook permanently"],
  // The fallback is mutated TOWARDS silence, not towards NaN. `return n` on a
  // garbage value disables the deadline, which fails open and is the direction
  // this hook is allowed to fail in — no fixture can observe it. `return 0`
  // models the regression that matters: a typo'd override mutes the guard.
  ["scan budget falls back to zero instead of the default",
   "return Number.isFinite(n) && n >= 0 ? n : 2000;",
   "return Number.isFinite(n) && n >= 0 ? n : 0;",
   "a non-numeric override mutes the hook instead of using the default"],
  ["exit code 1",
   "process.exit(0);\n}",
   "process.exit(1);\n}",
   "breaks 'always exits 0'"],

  // hooks.json's matcher and ownAgentName have to agree on the namespace. Three
  // mutants, because the pin can fail in three directions and only one is loud.
  ["a foreign namespace is stripped to its bare name",
   "  if (!agent.startsWith(SELF_NAMESPACE)) return null;\n  return agent.slice(SELF_NAMESPACE.length);",
   '  return agent.slice(agent.lastIndexOf(":") + 1);',
   "warns another plugin's fixer about a brief it never agreed to"],
  ["a bare name is accepted as ours",
   "  if (!agent.startsWith(SELF_NAMESPACE)) return null;",
   '  if (!agent.startsWith(SELF_NAMESPACE)) return agent.includes(":") ? null : agent;',
   "an unnamespaced `fixer`, which is not this plugin's, is held to this plugin's brief"],
  ["namespaced agents stop being checked",
   "  return agent.slice(SELF_NAMESPACE.length);\n}",
   "  return null;\n}",
   "omc-slim:fixer, the only spelling the binary presents, goes unchecked"],

  // --- A3 / C8: where the write landed ---------------------------------------
  ["outside-the-project write counted as a deliverable",
   'return sawSuccess ? "outside" : "none";',
   'return sawSuccess ? true : "none";',
   "C8 returns: a scratch write to /tmp silences the hook and the project is untouched"],
  ["containment test always passes",
   "  return path === root || path.startsWith(prefix);",
   "  return true;",
   "every write counts wherever it landed — C8 again, one layer down"],
  ["containment test always fails",
   "  return path === root || path.startsWith(prefix);",
   "  return false;",
   "every in-project write is reported as having landed outside"],
  ["a root already ending in the separator is doubled",
   "  const prefix = root.endsWith(sep) ? root : root + sep;",
   "  const prefix = root + sep;",
   "a project rooted at / has every write reported as outside it"],
  ["project root not symlink-resolved",
   "    return { real: realpathSync(cwd), raw: resolve(cwd) };",
   "    return { real: cwd, raw: resolve(cwd) };",
   "a cwd reached through a symlink makes every write look external"],
  ["the lexical containment test removed",
   "  if (root.raw !== null && withinRoot(resolve(root.raw, rawPath), root.raw)) {\n    return true;\n  }",
   "  if (false) {\n    return true;\n  }",
   "a write through a symlinked directory INSIDE the project is called outside it"],
  ["written path not symlink-resolved",
   "      return join(realpathSync(head), ...tail);",
   "      return resolve(base, path);",
   "a path spelled through a symlink makes an in-project write look external"],
  // The guess has to take the shape projectRoot returns. A bare string throws
  // inside the containment test and lands in the fail-open path, which is
  // silence, and a mutant that only crashes measures nothing.
  ["a missing cwd is guessed at rather than abstained on",
   '    debug("no cwd in payload; not testing where writes landed");\n    return null;',
   '    debug("no cwd in payload; not testing where writes landed");\n    return { real: "/nonexistent-project-root", raw: "/nonexistent-project-root" };',
   "a payload with no cwd turns every write into a false accusation"],
  ["a write with no path is placed anyway",
   '    if (typeof value === "string" && value.trim() !== "") return value;\n  }\n  return null;',
   '    if (typeof value === "string" && value.trim() !== "") return value;\n  }\n  return "/tmp/nowhere";',
   "a write-tool shape this hook does not know becomes an accusation"],
  ["an unplaceable write is treated as outside",
   "    if (root === null || path === null) return true;",
   '    if (root === null) return true;\n    if (path === null) return "outside";',
   "cannot-tell is reported as a verdict, which is the one thing this hook must not do"],
  ["the two write states collapse into one message",
   "advisories.push(outsideWriteAdvisory(bare));",
   "advisories.push(noWriteAdvisory(bare));",
   "a /tmp-only run is reported as 'no write tool was used', which is false"],
  ["notebook_path stops being read",
   '  for (const key of ["file_path", "notebook_path"]) {',
   '  for (const key of ["file_path"]) {',
   "every NotebookEdit becomes an unplaceable write"],
  ["suppressOutput dropped",
   "JSON.stringify({ suppressOutput: true })",
   "JSON.stringify({})",
   "raw JSON may surface to the user"],
  ["attempted write counts as a deliverable",
   "    if (!succeeded.has(id)) continue;",
   "    if (false) continue;",
   "the original bug the hook was written to avoid: a denied Edit becomes a deliverable"],

  // --- state 3: a verification result nothing in the transcript ran ----------
  // String.raw where the anchor carries a regex: the hook's own source holds a
  // literal backslash there, and an ordinary quoted string would have to double
  // every one of them to say the same thing.
  ["a check command is never recorded",
   '  if (verdicts.has("check")) scan.checkRuns.add(node.id);',
   "  if (false) scan.checkRuns.add(node.id);",
   "a real `npm test` stops counting, and every honest run is told its result is a claim"],
  ["every Bash command counts as a check",
   '  if (verdicts.has("check")) scan.checkRuns.add(node.id);',
   "  scan.checkRuns.add(node.id);",
   "`git status` silences the state, which is how it stops existing"],
  ["a failed check counts as a clean one",
   "  for (const id of scan.checkRuns) {\n    if (scan.succeeded.has(id)) return true;",
   "  for (const id of scan.checkRuns) {\n    return true;",
   "a runner that exited non-zero answers a 'tests pass' written over its failure"],
  ["substring matching restored (git log --oneline latest silences)",
   "  const argv = tokenize(segment);",
   '  if (segment.toLowerCase().includes("test")) return "check";\n  const argv = tokenize(segment);',
   "the headline loophole: a git log whose message contains 'test' counts as a runner"],
  ["wrapper stripping disabled",
   "  const unwrapped = unwrap(argv);",
   "  const unwrapped = { argv, script: null };",
   "`timeout 60 pytest`, `uv run pytest` and `sudo npm test` read as unknown, and the state falls silent for every wrapped runner"],
  ["ci restored to the bare check words",
   'const SCRIPT_WORDS = new Set([...CHECK_WORDS, "ci"]);',
   'const SCRIPT_WORDS = new Set([...CHECK_WORDS, "ci"]);\nCHECK_WORDS.add("ci");',
   "`npm ci`, an install, silences a claim that nothing tested"],
  ["gradle back among the bare check binaries",
   '  "pylint",\n]);',
   '  "pylint",\n  "gradle",\n]);',
   "`gradle clean` silences a claim that nothing tested"],
  ["a delegated dispatch no longer counts",
   "scan.sawUnknownCommand || sawDelegation(scan)",
   "scan.sawUnknownCommand",
   "an agent that handed the checking to another agent is accused of not checking"],
  ["a failed dispatch counts as delegation",
   "  for (const id of scan.dispatches) {\n    if (scan.succeeded.has(id)) return true;",
   "  for (const id of scan.dispatches) {\n    return true;",
   "any Task that errored silences the state for the rest of the transcript"],
  ["the claim advisory never fires",
   "  if (claimed) advisories.push(unrunCheckAdvisory(bare));",
   "  if (false) advisories.push(unrunCheckAdvisory(bare));",
   "the whole state goes quiet while every other gate still reports green"],
  ["the claim advisory replaces the write advisory",
   "  if (claimed) advisories.push(unrunCheckAdvisory(bare));",
   '  if (claimed) return emit("omc-slim: " + unrunCheckAdvisory(bare));',
   "an agent that wrote nothing AND claimed a result is only told about one of them"],
  ["the two advisories collapse to the first",
   String.raw`advisories.join("\n")`,
   "advisories[0]",
   "the second state is dropped from a message that fired for both"],
  ["a reported failure counts as a claim",
   "    if (NOT_AN_ASSERTION.test(claimable)) continue;",
   "    if (false) continue;",
   "'2 tests failed' is flagged, which punishes exactly the honesty this asks for"],
  ["the hedge-word idiom pre-strip removed",
   '  return HEDGE_WORD_IDIOMS.reduce((text, phrase) => text.replace(phrase, " "), sentence);',
   "  return sentence;",
   "'all tests pass, no failures' reads as a hedge and the commonest real claim goes unflagged"],
  ["the final message is matched whole instead of sentence by sentence",
   "  for (const sentence of normalised.split(SENTENCE_END)) {",
   "  for (const sentence of [normalised]) {",
   "any real report saying 'no other files were touched' mutes the state"],
  ["a decimal point ends a sentence",
   String.raw`const SENTENCE_END = /(?<!\d)\.(?!\d)|[!?;\n]+/;`,
   String.raw`const SENTENCE_END = /[.!?;\n]+/;`,
   "'passed in 0.4s' is cut at the decimal and the runner's timed summary stops being recognised"],
  ["a missing final message is read as a claim",
   '  if (typeof message !== "string" || message.trim() === "") return false;\n  if (!assertsVerification(message)) return false;',
   '  if (typeof message === "string" && message.trim() !== "" && !assertsVerification(message)) return false;',
   "an agent that claimed nothing is told its claim is unverified"],
  // A self-contained fallback, defined inline in main where both transcript
  // paths are in scope: the shape the regression takes when someone decides an
  // absent field should be read from the file instead.
  ["falls back to the transcript's last assistant text",
   "  const lastMessage = data.last_assistant_message;",
   "  const lastMessage = data.last_assistant_message ?? lastAssistantTextIn(data.agent_transcript_path ?? data.transcript_path);\n" +
     "  function lastAssistantTextIn(path) {\n" +
     "    let last = null;\n" +
     '    for (const line of readFileSync(path, "utf8").split("\\n")) {\n' +
     "      try {\n" +
     "        const entry = JSON.parse(line);\n" +
     '        if (entry.type !== "assistant") continue;\n' +
     '        const text = entry.message.content.filter((b) => b.type === "text").map((b) => b.text).join("\\n");\n' +
     '        if (text.trim() !== "") last = text;\n' +
     "      } catch {}\n" +
     "    }\n" +
     "    return last;\n" +
     "  }",
   "a transcript flushed on a timer supplies an earlier message as the final one, and the field's absence stops meaning abstain"],
  // Flipped to accuse rather than removed: removed, the null reaches the next
  // clause, throws, and lands in the fail-open path, which is silence and
  // measures nothing.
  ["a claim is asserted against a transcript that could not be read",
   "  if (scan === null) return false;",
   "  if (scan === null) return true;",
   "cannot-tell becomes an accusation, which is the one thing this hook must not do"],

  // Each phrasing in the vocabulary is dropped on its own. A narrowing that no
  // case notices is how a state keeps its tests and loses its coverage.
  ["'tests pass' stops counting as a claim",
   String.raw`  /\b(tests?|suites?|specs?)\s+(all\s+)?(pass|passes|passed|passing)\b/,`,
   "  /(?!)/,",
   "the commonest phrasing of all stops being recognised"],
  ["'N/N passed' stops counting as a claim",
   String.raw`  /\b\d+\s*\/\s*\d+\s+(tests?\s+)?(pass|passes|passed|passing|green)\b/,`,
   "  /(?!)/,",
   "the count-shaped claim the benchmark actually produced stops being recognised"],
  ["'N of N passed' stops counting as a claim",
   String.raw`  /\b\d+\s+of\s+\d+\s+(tests?\s+)?(pass|passes|passed|passing)\b/,`,
   "  /(?!)/,",
   "the spelled-out count stops being recognised"],
  ["'N passed' stops counting as a claim",
   String.raw`  /\b\d+\s+passed\b/,`,
   "  /(?!)/,",
   "the runner's own summary line, quoted back with nothing run, stops being recognised"],
  ["'passed in N s' stops counting as a claim",
   String.raw`  /\bpassed\s+in\s+[\d.]+\s*s\b/,`,
   "  /(?!)/,",
   "a timed summary line, quoted back with nothing run, stops being recognised"],
  ["'build succeeded' stops counting as a claim",
   String.raw`  /\bbuild\s+(is\s+)?(succeeded|successful|success|passed|passes|clean|green)\b/,`,
   "  /(?!)/,",
   "a build reported successful with no build run stops being recognised"],
  ["'typecheck clean' stops counting as a claim",
   String.raw`  /\b(type-?checks?|typechecking|tsc|mypy|lint|linting|linter|eslint|ruff)\s+(is\s+|are\s+|came\s+back\s+)?(clean|passes|passed|green)\b/,`,
   "  /(?!)/,",
   "a clean typecheck or lint reported with neither run stops being recognised"],
  ["'all green' stops counting as a claim",
   String.raw`  /\ball\s+green\b/,`,
   "  /(?!)/,",
   "the shortest claim of all stops being recognised"],
  ["'verified' beside the name of a check stops counting as a claim",
   "    if (VERIFIED.test(claimable) && VERIFIED_SUBJECT.test(claimable)) return true;",
   "    if (false) return true;",
   "'verified against the build', with nothing run, stops being recognised"],
  ["'verified' counts without the name of a check",
   "    if (VERIFIED.test(claimable) && VERIFIED_SUBJECT.test(claimable)) return true;",
   "    if (VERIFIED.test(claimable)) return true;",
   "audit prose — 'all eleven verified', 'grep-verified' — is flagged as an unrun test"],

  // --- the three command verdicts ----------------------------------------------
  ["an unknown command no longer abstains",
   '  if (verdicts.has("unknown")) scan.sawUnknownCommand = true;',
   "  if (false) scan.sawUnknownCommand = true;",
   "`python analyze.py` followed by 'tests pass' is accused, though the script may be the suite"],
  ["a non-check binary reads as unknown",
   '  if (NON_CHECK_BINARIES.has(bin)) return "non-check";',
   '  if (NON_CHECK_BINARIES.has(bin)) return "unknown";',
   "`git status` mutes the advisory, and a turn that only looked around is never flagged"],
  ["an unrecognised binary is accused",
   '  if (isScriptPath(tokens[0])) return scriptVerdict(tokens[0]);\n  return "unknown";',
   '  if (isScriptPath(tokens[0])) return scriptVerdict(tokens[0]);\n  return "non-check";',
   "a runner the tables do not name is treated as proof nothing ran"],
  ["quotes no longer protect operators",
   "    if (ch === \"'\" || ch === '\"') {\n      quote = ch;",
   "    if (false) {\n      quote = ch;",
   "`git commit -m \"wip\\nnpm test\"` is split inside the message and reads as a test run"],
  ["a heredoc body is read as commands",
   '    if (ch === "<" && command[i + 1] === "<") {',
   "    if (false) {",
   "`cat <<EOF` followed by 'npm test' in the body counts as a test run"],
  ["a heredoc body resumes as commands",
   "      const bodyEnd = heredocBodyEnd(command, i, heredoc);",
   "      const bodyEnd = i;",
   "the operator is seen and the body is scanned anyway: 'npm test' inside it counts as a test run"],
  ["an arithmetic shift is read as a heredoc",
   "  if (!startsWord(command, i, segmentStart)) return null;\n",
   "",
   "`x=$((1<<2)); npm test` swallows its line as a heredoc, and the runner behind it stops counting"],
  ["subshell parens are read as argv",
   "    .map(bareToken)",
   "    .map((token) => token.replace(/^['\"]|['\"]$/g, \"\"))",
   "`(cd sub && npm test) 2>&1 | tail -20` reads `test)`, and the runner stops counting"],
  ["a comment is read as a command",
   '    if (ch === "#" && startsWord(command, i, start)) {',
   "    if (false) {",
   "`# run tests` reads as a command named `#`, unknown, and mutes the turn"],
  ["an error on a line of several commands is charged to the check",
   '  if (verdicts.has("check") && segments.length > 1) scan.multiSegmentCheckRuns.add(node.id);',
   "  if (false) scan.multiSegmentCheckRuns.add(node.id);",
   "`npm test && git commit` failing at the commit accuses a true 'All tests pass.'"],
  ["a task-runner run target is not inspected",
   '    const target = positional[positional.length - 1];',
   '    return "non-check"; const target = positional[positional.length - 1];',
   "nx run app:test is scored non-check and an honest run is accused"],
  ["check flags promote a non-check binary",
   '  if (NON_CHECK_BINARIES.has(bin)) return "non-check";\n  if (hasCheckWord(args, CHECK_FLAGS)) return "check";',
   '  if (hasCheckWord(args, CHECK_FLAGS)) return "check";\n  if (NON_CHECK_BINARIES.has(bin)) return "non-check";',
   "grep -- --check silences a claim no check answered"],
  ["an unlisted make target reads as non-check",
   '  return targets.every((target) => NON_CHECK_SUBCOMMANDS.has(target)) ? "non-check" : "unknown";',
   '  return "non-check";',
   "`make ci` is treated as proof nothing ran"],
  ["an unlisted toolchain subcommand reads as non-check",
   '  return NON_CHECK_SUBCOMMANDS.has(subcommand.toLowerCase()) ? "non-check" : "unknown";',
   '  return "non-check";',
   "`rake spec` and `nx affected` are treated as proof nothing ran"],
  ["the --check flag no longer makes a check",
   '  if (hasCheckWord(args, CHECK_FLAGS)) return "check";\n',
   "",
   "`cargo fmt --check` reads as a format, and the honest run is accused"],
  ["compile dropped from the check words",
   '  "compile",\n',
   "",
   "`mix compile` and `sbt compile` read as unknown, and the state falls silent on them"],
  ["leading shell keywords are read as argv0",
   "  while (i < tokens.length && SHELL_KEYWORDS.has(tokens[i])) i++;",
   "  while (false) i++;",
   "`if npm test; then` reads as a command named `if`, unknown, and the runner inside it stops counting"],
  ["the quadratic split regex restored",
   "  const segments = commandSegments(command);",
   String.raw`  const segments = command.split(/\s*(?:&&|\|\||;|\n|\|)\s*/);`,
   "one long command line stalls the hook past the 5 s hooks.json allows"],
  ["run-wrapper options are read as the command",
   "      tokens = dropOptions(tokens.slice(2), RUN_WRAPPER_VALUED);",
   "      tokens = tokens.slice(2);",
   "`uv run --frozen pytest` reads as a command named `--frozen`, and the runner behind it stops counting"],
  ["the token cap removed",
   '  if (argv.length > MAX_SEGMENT_TOKENS) return "unknown";',
   '  if (false) return "unknown";',
   "a generated line of wrappers is unwrapped to nothing and called a non-check"],
  ["the Windows launcher suffix is kept",
   String.raw`  return name.replace(/\.(exe|cmd|bat)$/, "");`,
   "  return name;",
   "`jest.cmd` and `pytest.exe` stop counting, and every Windows run is accused"],
  ["a bare make is not the build",
   '  if (targets.length === 0) return "check";',
   '  if (targets.length === 0) return "non-check";',
   "`make` and `make -j8`, which build the default target, count as proof nothing ran"],
  ["the docker command is judged from the container name",
   "  const afterContainer = dropDockerOptions(rest.slice(1)).slice(1);",
   "  const afterContainer = dropDockerOptions(rest.slice(1));",
   "`docker compose exec web pytest` reads as a command named `web`"],
  ["a script's name never says it is a check",
   '  return CHECK_SCRIPT_NAME.test(basenameArg(token)) ? "check" : "unknown";',
   '  return "unknown";',
   "`./run_tests.sh` and `scripts/check-coverage.sh` stop counting"],
  ["every script is a check",
   '  return CHECK_SCRIPT_NAME.test(basenameArg(token)) ? "check" : "unknown";',
   '  return "check";',
   "`./deploy.sh` silences a claim that nothing tested"],
  ["manage.py runs no check",
   '    return hasCheckWord(args.slice(scriptAt + 1), CHECK_WORDS) ? "check" : "unknown";',
   '    return "unknown";',
   "`python manage.py test` stops counting"],
  ["a coverage report is a check",
   '  if (args[0].toLowerCase() !== "run") return "non-check";',
   '  if (args[0].toLowerCase() !== "run") return "check";',
   "`coverage report` silences a claim that nothing tested"],
  ["a package script's name never says it is a check",
   '  return scriptLooksLikeCheck(script) ? "check" : "unknown";',
   '  return "unknown";',
   "`npm run test-unit` and `npm run check:types` stop counting"],

  // Stop: systemMessage only, bounded to the current turn.
  ["Stop emits additionalContext (a continue)",
   '    "result is a claim, not an observation.";\n  return emit(message);',
   '    "result is a claim, not an observation.";\n' +
     "  process.stdout.write(\n" +
     "    JSON.stringify({\n" +
     "      systemMessage: message,\n" +
     "      suppressOutput: true,\n" +
     '      hookSpecificOutput: { hookEventName: "Stop", additionalContext: "x" },\n' +
     "    }),\n" +
     "  );\n" +
     "  process.exit(0);",
   "additionalContext on Stop continues the turn under the block-cap loop protections"],
  ["Stop blocks the turn",
   '    "result is a claim, not an observation.";\n  return emit(message);',
   '    "result is a claim, not an observation.";\n' +
     "  process.stdout.write(\n" +
     '    JSON.stringify({ systemMessage: message, suppressOutput: true, decision: "block", reason: message }),\n' +
     "  );\n" +
     "  process.exit(0);",
   "decision:block is the oh-my-claudecode Stop deadlock"],
  ["stop_hook_active still injects",
   "  if (data.stop_hook_active === true) {\n    return emit(null);",
   "  if (false) {\n    return emit(null);",
   "a reminder stacks on the continue some other hook caused"],
  ["Stop reads the subagent transcript",
   "  const transcript = data.transcript_path ?? null;",
   "  const transcript = data.agent_transcript_path ?? data.transcript_path ?? null;",
   "a child npm test silences a parent that never ran one"],
  ["Stop credits a check from an earlier turn",
   "  const scan = scanTranscript(transcript, { lastTurnOnly: true });",
   "  const scan = scanTranscript(transcript);",
   "an npm test from turn 2 silences a tests-pass at turn 40"],
  ["a compaction summary opens a turn",
   "  if (entry.isMeta === true || entry.isCompactSummary === true) return false;",
   "  if (entry.isMeta === true) return false;",
   "the evidence before a compaction is discarded, and the turn's own npm test stops counting"],
  ["an isMeta line opens a turn",
   "  if (entry.isMeta === true || entry.isCompactSummary === true) return false;",
   "  if (entry.isCompactSummary === true) return false;",
   "a harness note filed under the user role resets the turn, and the npm test before it stops counting"],
  ["harness-written user text opens a turn",
   "  return !HARNESS_TEXT_PREFIXES.some((prefix) => text.startsWith(prefix));",
   "  return true;",
   "a background agent finishing resets the turn, and the npm test before it stops counting"],
  ["a system reminder opens a turn",
   '  "<system-reminder>",\n  "<command-name>",',
   '  "<command-name>",',
   "an injected reminder resets the turn, and the npm test before it stops counting"],
  ["a command message opens a turn",
   '  "<command-message>",\n  "<local-command-stdout>",',
   '  "<local-command-stdout>",',
   "a slash command's message resets the turn, and the npm test before it stops counting"],
  ["a turn with no assistant entry is judged",
   "  if (!scan.sawAssistantEntry) {",
   "  if (false) {",
   "a transcript the harness has not flushed yet is judged as a turn that ran nothing"],
  ["the long-line bail removed",
   "    if (pending.length > MAX_LINE_CHUNKS) {",
   "    if (false) {",
   "one very long line is joined chunk by chunk, and the read costs its length squared"],

  // The FileChanged ledger: only a row this agent could have caused abstains.
  ["ledger never silences a no-write",
   '  if (\n    (wrote === "none" || wrote === "outside") &&\n    scan.sawOpaqueTool &&\n    ledgerShowsInProjectWrite(data.cwd, root, data.session_id, scan.earliestTimestampMs)\n  ) {\n    wrote = null;',
   "  if (false) {\n    wrote = null;",
   "Auto-mode Bash writes are reported as 'no write tool was used'"],
  ["the outside-write state stops consulting the ledger",
   '    (wrote === "none" || wrote === "outside") &&',
   '    wrote === "none" &&',
   "'nothing in the project changed' is said over a ledger row that says otherwise"],
  ["the ledger is consulted for an agent that ran no shell or MCP tool",
   "    scan.sawOpaqueTool &&\n",
   "",
   "another fixer's write in the same session silences an agent that only read"],
  ["an MCP tool is not an opaque write",
   '    if (node.name === "Bash" || isMcpTool(node.name)) scan.sawOpaqueTool = true;',
   '    if (node.name === "Bash") scan.sawOpaqueTool = true;',
   "a write through an MCP filesystem server is reported as 'no write tool was used'"],
  ["ledger rows from other sessions count",
   "  if (row.session_id !== sessionId) return false;",
   "  if (false) return false;",
   "another conversation's write silences this agent's no-write state"],
  ["a ledger row without a session_id counts",
   "  if (row.session_id !== sessionId) return false;",
   '  if (typeof row.session_id === "string" && row.session_id !== sessionId) return false;',
   "a row the writer never produces vouches for a write nobody can place"],
  ["the ledger is consulted for a payload without a session_id",
   '  if (root === null || typeof sessionId !== "string" || sessionId === "") return false;',
   "  if (root === null) return false;",
   "with nothing to match against, an unscoped row silences the no-write state"],
  ["ledger rows from before the transcript count",
   '  return typeof row.t === "number" && row.t >= sinceMs - MTIME_TOLERANCE_MS;',
   "  return true;",
   "a write from before the agent existed silences its no-write state"],
  ["the mtime tolerance removed",
   "row.t >= sinceMs - MTIME_TOLERANCE_MS",
   "row.t >= sinceMs",
   "a write in the same second as the transcript's first line is dated before the agent existed"],
  ["a ledger unlink counts as a write",
   '  if (row.event === "unlink") return false;',
   "  if (false) return false;",
   "deleting a project file silences the no-write state"],
  ["a ledger row outside the project counts",
   "ledgerRowCounts(row, sessionId, sinceMs) && writeIsInProject(row.path, root)",
   "ledgerRowCounts(row, sessionId, sinceMs)",
   "a write to /tmp recorded in this session silences the no-write state"],
  ["a symlinked ledger is followed",
   "    const st = lstatSync(path);",
   "    const st = lstatSync(realpathSync(path));",
   "a symlink planted at the ledger path reads whatever it points at as this project's ledger"],
  ["the ledger size cap removed",
   "    if (!st.isFile() || st.size > MAX_LEDGER_BYTES) return false;",
   "    if (!st.isFile()) return false;",
   "a ledger the writer could not have produced is read whole, inside a 5 s hook"],
  ["the earliest timestamp becomes the latest",
   "  if (scan.earliestTimestampMs === null || ms < scan.earliestTimestampMs) {",
   "  if (scan.earliestTimestampMs === null || ms > scan.earliestTimestampMs) {",
   "the transcript is dated by its last line, and every write made during the run is too early to count"],
];

process.exit(
  await runMutants({
    hook: join(HERE, "verify-deliverables.mjs"),
    test: join(HERE, "verify-deliverables.test.mjs"),
    mutants: MUTANTS,
  }),
);
