#!/usr/bin/env node
/**
 * omc-slim — mutation check for the verify-deliverables harness.
 *
 * Breaks the hook on purpose, and asserts the harness notices every time. A
 * SURVIVED line is a hole in the tests, not a bug in the hook. Several mutants
 * here — `additionalContext`, `continue: false`, `decision: "block"` — re-enter
 * or halt a session while still exiting 0, which is what an exit-code assertion
 * alone cannot see.
 *
 * Two regressions are left out because no fixture can observe them, and a
 * mutant nothing can kill measures nothing. Restoring recursion to `unwrap`: a
 * segment is capped at 64 tokens before it is unwrapped, so the deepest
 * recursion that cap admits cannot overflow a stack. Starting Stop's tail read
 * at offset 0: that is the whole-file read, and it reaches the same verdicts
 * more slowly.
 *
 * The runner it calls is shared with the other hooks' mutation suites and holds
 * the sandbox discipline: mutants go to a temp copy, and the tracked hook is
 * only ever read.
 *
 * Run: node hooks/verify-deliverables.mutate.mjs
 */

import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { runMutants } from "./mutate-runner.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));

/**
 * [label, find, replace, what breaks in production]
 */
const MUTANTS = [
  ["additionalContext emitted",
   "JSON.stringify({ systemMessage: message, suppressOutput: true })",
   'JSON.stringify({ systemMessage: message, suppressOutput: true, hookSpecificOutput: { additionalContext: "x" } })',
   "re-injects into the finishing subagent"],
  ["continue:false emitted",
   "JSON.stringify({ suppressOutput: true })",
   'JSON.stringify({ suppressOutput: true, continue: false, stopReason: "x" })',
   "halts the session while exiting 0"],
  ["debug writes to stdout",
   'console.error("[omc-slim]", ...args)',
   'console.log("[omc-slim]", ...args)',
   "corrupts the JSON payload"],
  ["scan deadline removed",
   "if ((scanned++ & 0xff) === 0 && Date.now() >= deadline) {",
   "if (false) {",
   "unbounded scan on a pathological transcript, and the 5 s in hooks.json is advisory"],
  // Mutated to return the evidence gathered so far: the scan is a collection,
  // and answering from one that stopped early is the shape the wrong
  // implementation takes.
  ["scan deadline accuses instead of abstaining",
   'debug("cannot tell: scan budget exhausted", scanned);\n      return null;',
   'debug("cannot tell: scan budget exhausted", scanned);\n      return scan;',
   "a slow scan becomes a false accusation against an agent that did write"],
  ["cap check removed",
   "if (size - end >= MAX_TRANSCRIPT_BYTES) {",
   "if (false) {",
   "unbounded backward read"],
  ["regular-file check removed",
   "if (!st.isFile()) {",
   "if (false) {",
   "hangs forever on a FIFO or character device, breaking 'always exits 0'"],
  ["lstat weakened to stat",
   "st = lstatSync(transcriptPath);",
   "st = statSync(transcriptPath);",
   "follows a symlink to an arbitrary path"],
  ["failed tool_result counts as success",
   "node.is_error !== true",
   "true",
   "a denied write becomes a deliverable"],
  ["depth bound cut to 2",
   "if (depth > 6 ||",
   "if (depth > 2 ||",
   "misses real blocks at depth 3"],
  ["blank scan budget parsed as zero",
   'if (raw === undefined || raw.trim() === "") return 2000;',
   "if (raw === undefined) return 2000;",
   "an exported-but-empty override mutes the hook permanently"],
  // The fallback is mutated TOWARDS silence, not towards NaN. `return n` on a
  // garbage value disables the deadline, which fails open and is the direction
  // this hook is allowed to fail in — no fixture can observe it. `return 0`
  // models the regression that matters: a typo'd override mutes the guard.
  ["scan budget falls back to zero instead of the default",
   "return Number.isFinite(n) && n >= 0 ? n : 2000;",
   "return Number.isFinite(n) && n >= 0 ? n : 0;",
   "a non-numeric override mutes the hook instead of using the default"],
  ["exit code 1",
   "process.exit(0);\n}",
   "process.exit(1);\n}",
   "breaks 'always exits 0'"],

  ["suppressOutput dropped",
   "JSON.stringify({ suppressOutput: true })",
   "JSON.stringify({})",
   "raw JSON may surface to the user"],
  ["a check command is never recorded",
   '  if (verdicts.has("check")) scan.checkRuns.add(node.id);',
   "  if (false) scan.checkRuns.add(node.id);",
   "a real `npm test` stops counting, and every honest run is told its result is a claim"],
  ["every Bash command counts as a check",
   '  if (verdicts.has("check")) scan.checkRuns.add(node.id);',
   "  scan.checkRuns.add(node.id);",
   "`git status` silences the state, which is how it stops existing"],
  ["a failed check counts as a clean one",
   "  for (const id of scan.checkRuns) {\n    if (scan.succeeded.has(id)) return true;",
   "  for (const id of scan.checkRuns) {\n    return true;",
   "a runner that exited non-zero answers a 'tests pass' written over its failure"],
  ["substring matching restored (git log --oneline latest silences)",
   "  const argv = tokenize(segment);",
   '  if (segment.toLowerCase().includes("test")) return "check";\n  const argv = tokenize(segment);',
   "the headline loophole: a git log whose message contains 'test' counts as a runner"],
  ["wrapper stripping disabled",
   "  const unwrapped = unwrap(argv);",
   "  const unwrapped = { argv, script: null };",
   "`timeout 60 pytest`, `uv run pytest` and `sudo npm test` read as unknown, and the state falls silent for every wrapped runner"],
  ["ci restored to the bare check words",
   'const SCRIPT_WORDS = new Set([...CHECK_WORDS, "ci"]);',
   'const SCRIPT_WORDS = new Set([...CHECK_WORDS, "ci"]);\nCHECK_WORDS.add("ci");',
   "`npm ci`, an install, silences a claim that nothing tested"],
  ["gradle back among the bare check binaries",
   '  "pylint",\n]);',
   '  "pylint",\n  "gradle",\n]);',
   "`gradle clean` silences a claim that nothing tested"],
  ["a delegated dispatch no longer counts",
   "scan.sawUnknownCommand || sawDelegation(scan)",
   "scan.sawUnknownCommand",
   "an agent that handed the checking to another agent is accused of not checking"],
  ["a failed dispatch counts as delegation",
   "  for (const id of scan.dispatches) {\n    if (scan.succeeded.has(id)) return true;",
   "  for (const id of scan.dispatches) {\n    return true;",
   "any Task that errored silences the state for the rest of the transcript"],
  ["the claim advisory never fires",
   "  if (!claimed) return emit(null);",
   "  if (true) return emit(null);",
   "the whole state goes quiet while every other gate still reports green"],
  ["a reported failure counts as a claim",
   "    if (NOT_AN_ASSERTION.test(claimable)) continue;",
   "    if (false) continue;",
   "'2 tests failed' is flagged, which punishes exactly the honesty this asks for"],
  ["the hedge-word idiom pre-strip removed",
   '  return HEDGE_WORD_IDIOMS.reduce((text, phrase) => text.replace(phrase, " "), sentence);',
   "  return sentence;",
   "'all tests pass, no failures' reads as a hedge and the commonest real claim goes unflagged"],
  ["the final message is matched whole instead of sentence by sentence",
   "  for (const sentence of normalised.split(SENTENCE_END)) {",
   "  for (const sentence of [normalised]) {",
   "any real report saying 'no other files were touched' mutes the state"],
  ["a decimal point ends a sentence",
   String.raw`const SENTENCE_END = /(?<!\d)\.(?!\d)|[!?;\n]+/;`,
   String.raw`const SENTENCE_END = /[.!?;\n]+/;`,
   "'passed in 0.4s' is cut at the decimal and the runner's timed summary stops being recognised"],
  ["a missing final message is read as a claim",
   '  if (typeof message !== "string" || message.trim() === "") return false;\n  if (!assertsVerification(message)) return false;',
   '  if (typeof message === "string" && message.trim() !== "" && !assertsVerification(message)) return false;',
   "an agent that claimed nothing is told its claim is unverified"],
  // A self-contained fallback, defined inline in main where both transcript
  // paths are in scope: the shape the regression takes when someone decides an
  // absent field should be read from the file instead.
  ["falls back to the transcript's last assistant text",
   "  return mainStop(data, data.last_assistant_message);",
   "  return mainStop(data, data.last_assistant_message ?? \"All tests pass.\");",
   "a transcript flushed on a timer supplies an earlier message as the final one, and the field's absence stops meaning abstain"],
  ["a claim is asserted against a transcript that could not be read",
   "  if (scan === null) return false;",
   "  if (scan === null) return true;",
   "cannot-tell becomes an accusation, which is the one thing this hook must not do"],

  // Each phrasing in the vocabulary is dropped on its own. A narrowing that no
  // case notices is how a state keeps its tests and loses its coverage.
  ["'tests pass' stops counting as a claim",
   String.raw`  /\b(tests?|suites?|specs?)\s+(all\s+)?(pass|passes|passed|passing)\b/,`,
   "  /(?!)/,",
   "the commonest phrasing of all stops being recognised"],
  ["'N/N passed' stops counting as a claim",
   String.raw`  /\b\d+\s*\/\s*\d+\s+(tests?\s+)?(pass|passes|passed|passing|green)\b/,`,
   "  /(?!)/,",
   "the count-shaped claim the benchmark actually produced stops being recognised"],
  ["'N of N passed' stops counting as a claim",
   String.raw`  /\b\d+\s+of\s+\d+\s+(tests?\s+)?(pass|passes|passed|passing)\b/,`,
   "  /(?!)/,",
   "the spelled-out count stops being recognised"],
  ["'N passed' stops counting as a claim",
   String.raw`  /\b\d+\s+passed\b/,`,
   "  /(?!)/,",
   "the runner's own summary line, quoted back with nothing run, stops being recognised"],
  ["'passed in N s' stops counting as a claim",
   String.raw`  /\bpassed\s+in\s+[\d.]+\s*s\b/,`,
   "  /(?!)/,",
   "a timed summary line, quoted back with nothing run, stops being recognised"],
  ["'build succeeded' stops counting as a claim",
   String.raw`  /\bbuild\s+(is\s+)?(succeeded|successful|success|passed|passes|clean|green)\b/,`,
   "  /(?!)/,",
   "a build reported successful with no build run stops being recognised"],
  ["'typecheck clean' stops counting as a claim",
   String.raw`  /\b(type-?checks?|typechecking|tsc|mypy|lint|linting|linter|eslint|ruff)\s+(is\s+|are\s+|came\s+back\s+)?(clean|passes|passed|green)\b/,`,
   "  /(?!)/,",
   "a clean typecheck or lint reported with neither run stops being recognised"],
  ["'all green' stops counting as a claim",
   String.raw`  /\ball\s+green\b/,`,
   "  /(?!)/,",
   "the shortest claim of all stops being recognised"],
  ["'verified' beside the name of a check stops counting as a claim",
   "    if (VERIFIED.test(claimable) && VERIFIED_SUBJECT.test(claimable)) return true;",
   "    if (false) return true;",
   "'verified against the build', with nothing run, stops being recognised"],
  ["'verified' counts without the name of a check",
   "    if (VERIFIED.test(claimable) && VERIFIED_SUBJECT.test(claimable)) return true;",
   "    if (VERIFIED.test(claimable)) return true;",
   "audit prose — 'all eleven verified', 'grep-verified' — is flagged as an unrun test"],

  // --- the three command verdicts ----------------------------------------------
  ["an unknown command no longer abstains",
   '  if (verdicts.has("unknown")) scan.sawUnknownCommand = true;',
   "  if (false) scan.sawUnknownCommand = true;",
   "`python analyze.py` followed by 'tests pass' is accused, though the script may be the suite"],
  ["a non-check binary reads as unknown",
   '  if (NON_CHECK_BINARIES.has(bin)) return "non-check";',
   '  if (NON_CHECK_BINARIES.has(bin)) return "unknown";',
   "`git status` mutes the advisory, and a turn that only looked around is never flagged"],
  ["an unrecognised binary is accused",
   '  if (isScriptPath(tokens[0])) return scriptVerdict(tokens[0]);\n  return "unknown";',
   '  if (isScriptPath(tokens[0])) return scriptVerdict(tokens[0]);\n  return "non-check";',
   "a runner the tables do not name is treated as proof nothing ran"],
  ["quotes no longer protect operators",
   "    if (ch === \"'\" || ch === '\"') {\n      quote = ch;",
   "    if (false) {\n      quote = ch;",
   "`git commit -m \"wip\\nnpm test\"` is split inside the message and reads as a test run"],
  ["a heredoc body is read as commands",
   '    if (ch === "<" && command[i + 1] === "<") {',
   "    if (false) {",
   "`cat <<EOF` followed by 'npm test' in the body counts as a test run"],
  ["a heredoc body resumes as commands",
   "      const bodyEnd = heredocBodyEnd(command, i, heredoc);",
   "      const bodyEnd = i;",
   "the operator is seen and the body is scanned anyway: 'npm test' inside it counts as a test run"],
  ["an arithmetic shift is read as a heredoc",
   "  if (!startsWord(command, i, segmentStart)) return null;\n",
   "",
   "`x=$((1<<2)); npm test` swallows its line as a heredoc, and the runner behind it stops counting"],
  ["subshell parens are read as argv",
   "    .map(bareToken)",
   "    .map((token) => token.replace(/^['\"]|['\"]$/g, \"\"))",
   "`(cd sub && npm test) 2>&1 | tail -20` reads `test)`, and the runner stops counting"],
  ["a comment is read as a command",
   '    if (ch === "#" && startsWord(command, i, start)) {',
   "    if (false) {",
   "`# run tests` reads as a command named `#`, unknown, and mutes the turn"],
  ["an error on a line of several commands is charged to the check",
   '  if (verdicts.has("check") && segments.length > 1) scan.multiSegmentCheckRuns.add(node.id);',
   "  if (false) scan.multiSegmentCheckRuns.add(node.id);",
   "`npm test && git commit` failing at the commit accuses a true 'All tests pass.'"],
  ["a task-runner run target is not inspected",
   '    const target = positional[positional.length - 1];',
   '    return "non-check"; const target = positional[positional.length - 1];',
   "nx run app:test is scored non-check and an honest run is accused"],
  ["check flags promote a non-check binary",
   '  if (NON_CHECK_BINARIES.has(bin)) return "non-check";\n  if (hasCheckWord(args, CHECK_FLAGS)) return "check";',
   '  if (hasCheckWord(args, CHECK_FLAGS)) return "check";\n  if (NON_CHECK_BINARIES.has(bin)) return "non-check";',
   "grep -- --check silences a claim no check answered"],
  ["an unlisted make target reads as non-check",
   '  return targets.every((target) => NON_CHECK_SUBCOMMANDS.has(target)) ? "non-check" : "unknown";',
   '  return "non-check";',
   "`make ci` is treated as proof nothing ran"],
  ["an unlisted toolchain subcommand reads as non-check",
   '  return NON_CHECK_SUBCOMMANDS.has(subcommand.toLowerCase()) ? "non-check" : "unknown";',
   '  return "non-check";',
   "`rake spec` and `nx affected` are treated as proof nothing ran"],
  ["the --check flag no longer makes a check",
   '  if (hasCheckWord(args, CHECK_FLAGS)) return "check";\n',
   "",
   "`cargo fmt --check` reads as a format, and the honest run is accused"],
  ["compile dropped from the check words",
   '  "compile",\n',
   "",
   "`mix compile` and `sbt compile` read as unknown, and the state falls silent on them"],
  ["leading shell keywords are read as argv0",
   "  while (i < tokens.length && SHELL_KEYWORDS.has(tokens[i])) i++;",
   "  while (false) i++;",
   "`if npm test; then` reads as a command named `if`, unknown, and the runner inside it stops counting"],
  ["the quadratic split regex restored",
   "  const segments = commandSegments(command);",
   String.raw`  const segments = command.split(/\s*(?:&&|\|\||;|\n|\|)\s*/);`,
   "one long command line stalls the hook past the 5 s hooks.json allows"],
  ["run-wrapper options are read as the command",
   "      tokens = dropOptions(tokens.slice(2), RUN_WRAPPER_VALUED);",
   "      tokens = tokens.slice(2);",
   "`uv run --frozen pytest` reads as a command named `--frozen`, and the runner behind it stops counting"],
  ["the token cap removed",
   '  if (argv.length > MAX_SEGMENT_TOKENS) return "unknown";',
   '  if (false) return "unknown";',
   "a generated line of wrappers is unwrapped to nothing and called a non-check"],
  ["the Windows launcher suffix is kept",
   String.raw`  return name.replace(/\.(exe|cmd|bat)$/, "");`,
   "  return name;",
   "`jest.cmd` and `pytest.exe` stop counting, and every Windows run is accused"],
  ["a bare make is not the build",
   '  if (targets.length === 0) return "check";',
   '  if (targets.length === 0) return "non-check";',
   "`make` and `make -j8`, which build the default target, count as proof nothing ran"],
  ["the docker command is judged from the container name",
   "  const afterContainer = dropDockerOptions(rest.slice(1)).slice(1);",
   "  const afterContainer = dropDockerOptions(rest.slice(1));",
   "`docker compose exec web pytest` reads as a command named `web`"],
  ["a script's name never says it is a check",
   '  return CHECK_SCRIPT_NAME.test(basenameArg(token)) ? "check" : "unknown";',
   '  return "unknown";',
   "`./run_tests.sh` and `scripts/check-coverage.sh` stop counting"],
  ["every script is a check",
   '  return CHECK_SCRIPT_NAME.test(basenameArg(token)) ? "check" : "unknown";',
   '  return "check";',
   "`./deploy.sh` silences a claim that nothing tested"],
  ["manage.py runs no check",
   '    return hasCheckWord(args.slice(scriptAt + 1), CHECK_WORDS) ? "check" : "unknown";',
   '    return "unknown";',
   "`python manage.py test` stops counting"],
  ["a coverage report is a check",
   '  if (args[0].toLowerCase() !== "run") return "non-check";',
   '  if (args[0].toLowerCase() !== "run") return "check";',
   "`coverage report` silences a claim that nothing tested"],
  ["a package script's name never says it is a check",
   '  return scriptLooksLikeCheck(script) ? "check" : "unknown";',
   '  return "unknown";',
   "`npm run test-unit` and `npm run check:types` stop counting"],

  // Stop: systemMessage only, bounded to the current turn.
  ["Stop emits additionalContext (a continue)",
   '    "result is a claim, not an observation.";\n  return emit(message);',
   '    "result is a claim, not an observation.";\n' +
     "  process.stdout.write(\n" +
     "    JSON.stringify({\n" +
     "      systemMessage: message,\n" +
     "      suppressOutput: true,\n" +
     '      hookSpecificOutput: { hookEventName: "Stop", additionalContext: "x" },\n' +
     "    }),\n" +
     "  );\n" +
     "  process.exit(0);",
   "additionalContext on Stop continues the turn under the block-cap loop protections"],
  ["Stop blocks the turn",
   '    "result is a claim, not an observation.";\n  return emit(message);',
   '    "result is a claim, not an observation.";\n' +
     "  process.stdout.write(\n" +
     '    JSON.stringify({ systemMessage: message, suppressOutput: true, decision: "block", reason: message }),\n' +
     "  );\n" +
     "  process.exit(0);",
   "decision:block is the oh-my-claudecode Stop deadlock"],
  ["stop_hook_active still injects",
   "  if (data.stop_hook_active === true) {\n    return emit(null);",
   "  if (false) {\n    return emit(null);",
   "a reminder stacks on the continue some other hook caused"],
  ["Stop reads the subagent transcript",
   "  const transcript = data.transcript_path ?? null;",
   "  const transcript = data.agent_transcript_path ?? data.transcript_path ?? null;",
   "a child npm test silences a parent that never ran one"],
  ["a compaction summary opens a turn",
   "  if (entry.isMeta === true || entry.isCompactSummary === true) return false;",
   "  if (entry.isMeta === true) return false;",
   "the evidence before a compaction is discarded, and the turn's own npm test stops counting"],
  ["an isMeta line opens a turn",
   "  if (entry.isMeta === true || entry.isCompactSummary === true) return false;",
   "  if (entry.isCompactSummary === true) return false;",
   "a harness note filed under the user role resets the turn, and the npm test before it stops counting"],
  ["harness-written user text opens a turn",
   "  return !HARNESS_TEXT_PREFIXES.some((prefix) => text.startsWith(prefix));",
   "  return true;",
   "a background agent finishing resets the turn, and the npm test before it stops counting"],
  ["a system reminder opens a turn",
   '  "<system-reminder>",\n  "<command-name>",',
   '  "<command-name>",',
   "an injected reminder resets the turn, and the npm test before it stops counting"],
  ["a command message opens a turn",
   '  "<command-message>",\n  "<local-command-stdout>",',
   '  "<local-command-stdout>",',
   "a slash command's message resets the turn, and the npm test before it stops counting"],
  ["a turn with no assistant entry is judged",
   "  if (!scan.sawAssistantEntry) {",
   "  if (false) {",
   "a transcript the harness has not flushed yet is judged as a turn that ran nothing"],
  ["the long-line bail removed",
   "    if (pending.length > MAX_LINE_CHUNKS) {",
   "    if (false) {",
   "one very long line is joined chunk by chunk, and the read costs its length squared"],

];

process.exit(
  await runMutants({
    hook: join(HERE, "verify-deliverables.mjs"),
    test: join(HERE, "verify-deliverables.test.mjs"),
    mutants: MUTANTS,
  }),
);
